basePath: /api
definitions:
  db.UsersRole:
    enum:
    - USER
    - ADMIN
    type: string
    x-enum-varnames:
    - UsersRoleUSER
    - UsersRoleADMIN
  handlers.LoginUserDto:
    properties:
      emailAddress:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      role:
        $ref: '#/definitions/db.UsersRole'
    type: object
  handlers.UserLoginRequest:
    properties:
      emailAddress:
        type: string
      password:
        type: string
    type: object
  handlers.UserLoginResponse:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
      user:
        $ref: '#/definitions/handlers.LoginUserDto'
    type: object
  handlers.UserRegistrationRequest:
    properties:
      emailAddress:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
    type: object
host: http://localhost:8080
info:
  contact:
    email: veronsajendra@gmail.com
    name: Veron Baranige
  description: This is a starter template for Echo with Keycloak & SQLC.
  title: Echo Keycloak Starter API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: User Login Request
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/handlers.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.UserLoginResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: User login
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: User Registration Request
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/handlers.UserRegistrationRequest'
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create new user account
      tags:
      - Auth
swagger: "2.0"
