root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "sqlc generate && go build -o ./tmp/main ./cmd/server"
  delay = 1000
  exclude_dir = ["tmp", "deployments", "test", "docs", "scripts"]
  exclude_file = []
  exclude_regex = ["_test.go", "_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["cmd", "internal/database/queries", "internal/auth", "internal/handlers", "internal/middleware", "internal/routes"]
  include_ext = ["go", "tpl", "sql"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false